baseURL = 'kazcomy.github.io'
languageCode = 'ja'
title = 'kazcomy'
enableRobotsTXT = true
theme = "PaperMod"

[taxonomies]
    tag = 'tags'

[params]
    ShowReadingTime = true
    ShowCodeCopyButtons = true
